### ISSUE TITLE
54595b13128576000257a3c1 in 8 keys

### ISSUE THREAD

**Issue by wehlutyk** [Delapouite/kakoune-tv#1]
First of all, this is a great learning resource!

I just realised that 54595b13128576000257a3c1 can be done with the following sequence: `e5Cc<c-r>#0<esc>`

(I can make a PR if you like, I was just lazy to set up the environment for such a small change)

**Comment by Delapouite** [comment]
Thanks !

This project is more about the recording and displaying than the real achievement of finding the best combinations of keys.
What KakouneTV does is blindly crawling the content available on this repo https://github.com/mawww/golf . So I guess it's a better place to contribute.
Then I could do a refresh of the underlying data on this project to update the keys and add more golf session.

**Comment by wehlutyk** [comment]
Indeed! Thanks for the tip, I moved this to mawww/golf#9 then.
